-- ==============================================================================
-- 02_raw_tables.sql
-- Create RAW source simulation tables, reference tables, and contract storage
-- ==============================================================================

USE DATABASE SC_ONTOLOGY;
USE SCHEMA RAW;
USE WAREHOUSE HACK_WH;

-- Reference Tables
CREATE OR REPLACE TABLE RAW.FX_RATES (
    YEAR_MONTH VARCHAR(7),        -- YYYY-MM
    BASE_CURRENCY VARCHAR(3),     -- EUR, VND, USD
    TARGET_CURRENCY VARCHAR(3),   -- USD
    EXCHANGE_RATE NUMBER(12,6),
    LAST_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.UOM_CONVERSIONS (
    FROM_UOM VARCHAR(10),
    TO_UOM VARCHAR(10),
    CONVERSION_FACTOR NUMBER(12,6),
    CATEGORY VARCHAR(20)          -- WEIGHT, COUNT, VOLUME
);

-- Master Data Tables
CREATE OR REPLACE TABLE RAW.ERP_PLANTS (
    PLANT_CODE VARCHAR(20) PRIMARY KEY,
    PLANT_NAME VARCHAR(100),
    CITY VARCHAR(100),
    COUNTRY_CODE VARCHAR(10),
    REGION VARCHAR(20),
    TZ_OFFSET VARCHAR(10)
);

CREATE OR REPLACE TABLE RAW.ERP_SUPPLIERS (
    VENDOR_ID VARCHAR(30) PRIMARY KEY,
    VENDOR_NAME VARCHAR(150),
    TIER_CODE VARCHAR(20),
    COUNTRY VARCHAR(50),
    STATUS_FLAG VARCHAR(10)
);

CREATE OR REPLACE TABLE RAW.ERP_PARTS (
    MATERIAL_NO VARCHAR(50) PRIMARY KEY,
    DESCRIPTION VARCHAR(200),
    COMMODITY_GROUP VARCHAR(50),
    BASE_UOM VARCHAR(10),
    STD_COST_LOCAL NUMBER(12,4),
    LOCAL_CURR VARCHAR(5),
    IS_CRITICAL_FLAG VARCHAR(5)
);

CREATE OR REPLACE TABLE RAW.ERP_PRODUCTS (
    MATNR_FG VARCHAR(50) PRIMARY KEY,
    PRODUCT_NAME VARCHAR(200),
    PROD_FAMILY VARCHAR(50),
    LIST_PRICE_USD NUMBER(12,2)
);

CREATE OR REPLACE TABLE RAW.ERP_CUSTOMERS (
    KUNNR VARCHAR(30) PRIMARY KEY,
    NAME_ORG VARCHAR(150),
    INDUSTRY_SECTOR VARCHAR(50),
    COUNTRY VARCHAR(50),
    REGION VARCHAR(20)
);

CREATE OR REPLACE TABLE RAW.LOGISTICS_CARRIERS (
    CARRIER_CODE VARCHAR(30) PRIMARY KEY,
    CARRIER_NAME VARCHAR(100),
    TRANSPORT_MODE VARCHAR(30),
    RELIABILITY_RATING NUMBER(3,2)
);

CREATE OR REPLACE TABLE RAW.ERP_BILL_OF_MATERIALS (
    BOM_ID VARCHAR(50) PRIMARY KEY,
    PARENT_MATNR VARCHAR(50),
    CHILD_MATNR VARCHAR(50),
    COMPONENT_QTY NUMBER(10,4),
    UOM VARCHAR(10),
    SCRAP_PCT NUMBER(5,2)
);

-- Transaction Tables (Messy strings, timestamps, and local values)
CREATE OR REPLACE TABLE RAW.ERP_PURCHASE_ORDERS (
    PO_LINE_ID VARCHAR(50) PRIMARY KEY,
    PO_HEADER_NO VARCHAR(50),
    VENDOR_CODE VARCHAR(50),
    MATERIAL_NUM VARCHAR(50),
    PLANT_CODE VARCHAR(20),
    ORDER_DATE_STR VARCHAR(30),
    PROMISED_DATE_STR VARCHAR(30),
    ORDER_QTY NUMBER(12,2),
    UNIT_COST_LOCAL NUMBER(12,4),
    CURR_CODE VARCHAR(5)
);

CREATE OR REPLACE TABLE RAW.ERP_GOODS_RECEIPTS (
    GR_LINE_ID VARCHAR(50) PRIMARY KEY,
    PO_LINE_REF VARCHAR(50),
    RECEIPT_DATE_STR VARCHAR(30),
    QUANTITY_RCVD NUMBER(12,2),
    INSPECTION_CODE VARCHAR(20),
    INBOUND_FREIGHT_LOCAL NUMBER(12,2),
    HANDLING_COST_LOCAL NUMBER(12,2),
    DUTY_COST_LOCAL NUMBER(12,2)
);

CREATE OR REPLACE TABLE RAW.ERP_SALES_ORDERS (
    SO_NUMBER VARCHAR(50) PRIMARY KEY,
    CUST_ID VARCHAR(50),
    SO_DATE_STR VARCHAR(30),
    REQ_DELIV_DATE_STR VARCHAR(30),
    PROMISED_DELIV_DATE_STR VARCHAR(30),
    HEADER_STATUS VARCHAR(20),
    TOTAL_VAL_USD NUMBER(14,2)
);

CREATE OR REPLACE TABLE RAW.ERP_SALES_ORDER_LINES (
    SO_LINE_ID VARCHAR(50) PRIMARY KEY,
    SO_NUMBER VARCHAR(50),
    PRODUCT_SKU VARCHAR(50),
    ORDER_QTY NUMBER(10,2),
    UNIT_PRICE_USD NUMBER(12,2),
    PLANT_FULFILL VARCHAR(20)
);

CREATE OR REPLACE TABLE RAW.ERP_INVENTORY_SNAPSHOTS (
    INV_SNAP_ID VARCHAR(50) PRIMARY KEY,
    SNAP_DATE_STR VARCHAR(30),
    PLANT_CODE VARCHAR(20),
    MATERIAL_NO VARCHAR(50),
    STOCK_ON_HAND NUMBER(12,2),
    SAFETY_STOCK_MIN NUMBER(12,2),
    DAILY_USAGE_30D NUMBER(12,2)
);

CREATE OR REPLACE TABLE RAW.LOGISTICS_SHIPMENTS (
    SHIPMENT_NO VARCHAR(50) PRIMARY KEY,
    SO_HEADER_REF VARCHAR(50),
    CARRIER_ID VARCHAR(50),
    ORIGIN_PLANT VARCHAR(20),
    DEST_CUSTOMER VARCHAR(50),
    DISPATCH_TS_STR VARCHAR(30),
    DELIVERY_TS_STR VARCHAR(30),
    STATUS VARCHAR(20),
    FREIGHT_CHARGE_USD NUMBER(10,2),
    HANDLING_CHARGE_USD NUMBER(10,2),
    IS_BACKORDERED_FLAG VARCHAR(5)
);

CREATE OR REPLACE TABLE RAW.LOGISTICS_SHIPMENT_LINES (
    SHIP_LINE_ID VARCHAR(50) PRIMARY KEY,
    SHIPMENT_NO VARCHAR(50),
    SO_LINE_REF VARCHAR(50),
    PRODUCT_ID VARCHAR(50),
    QTY_SHIPPED NUMBER(10,2),
    QTY_DELIVERED NUMBER(10,2)
);

CREATE OR REPLACE TABLE RAW.SUPPLIER_PORTAL_COMMITS (
    COMMIT_ID VARCHAR(50) PRIMARY KEY,
    PORTAL_SUPP_ID VARCHAR(50),
    PO_LINE_REF VARCHAR(50),
    ACKNOWLEDGED_DATE_STR VARCHAR(30),
    SUPPLIER_PROMISED_DATE VARCHAR(30),
    COMMITTED_QTY NUMBER(12,2)
);

CREATE OR REPLACE TABLE RAW.IOT_TELEMETRY (
    EVENT_ID VARCHAR(50) PRIMARY KEY,
    DEVICE_ID VARCHAR(50),
    SHIPMENT_NO VARCHAR(50),
    LATITUDE NUMBER(9,6),
    LONGITUDE NUMBER(9,6),
    TEMPERATURE_C NUMBER(5,2),
    SHOCK_G NUMBER(5,2),
    EVENT_TIMESTAMP TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE RAW.SUPPLIER_CONTRACTS (
    CONTRACT_ID VARCHAR(50) PRIMARY KEY,
    SUPPLIER_CODE VARCHAR(50),
    SUPPLIER_NAME VARCHAR(150),
    CONTRACT_TITLE VARCHAR(200),
    EFFECTIVE_DATE DATE,
    EXPIRATION_DATE DATE,
    TARGET_OTIF_PCT NUMBER(5,2),
    CONTRACT_LEAD_TIME_DAYS NUMBER(5,0),
    PENALTY_TERMS VARCHAR(1000),
    FULL_CONTRACT_TEXT VARCHAR(16777216)
);
