-- ==============================================================================
-- 04_legacy_views.sql
-- Create 3 Disparate LEGACY Views Illustrating the "Before" Consistency Problem
-- ==============================================================================

USE DATABASE SC_ONTOLOGY;
USE SCHEMA LEGACY;
USE WAREHOUSE HACK_WH;

-- 1. PLANNING TEAM VIEW:
-- Measures OTD based on Plant Dispatch Date vs Promised Date (ignores customer transit time)
CREATE OR REPLACE VIEW LEGACY.VW_PLANNING_OTD AS
SELECT 
    DATE_TRUNC('month', TRY_TO_DATE(so.SO_DATE_STR, 'YYYY-MM-DD')) AS ORDER_MONTH,
    CASE 
        WHEN DATE_TRUNC('month', TRY_TO_DATE(so.SO_DATE_STR, 'YYYY-MM-DD')) BETWEEN '2026-07-01' AND '2026-09-30' THEN 'Q3 2026'
        ELSE 'OTHER'
    END AS QUARTER_LABEL,
    COUNT(s.SHIPMENT_NO) AS TOTAL_SHIPMENTS,
    COUNT(CASE 
        WHEN TRY_TO_DATE(SUBSTRING(s.DISPATCH_TS_STR, 1, 10), 'YYYY-MM-DD') <= TRY_TO_DATE(so.PROMISED_DELIV_DATE_STR, 'YYYY-MM-DD') THEN 1 
    END) AS ON_TIME_DISPATCH_COUNT,
    ROUND(100.0 * COUNT(CASE 
        WHEN TRY_TO_DATE(SUBSTRING(s.DISPATCH_TS_STR, 1, 10), 'YYYY-MM-DD') <= TRY_TO_DATE(so.PROMISED_DELIV_DATE_STR, 'YYYY-MM-DD') THEN 1 
    END) / NULLIF(COUNT(s.SHIPMENT_NO), 0), 2) AS PLANNING_OTD_PCT
FROM RAW.ERP_SALES_ORDERS so
JOIN RAW.LOGISTICS_SHIPMENTS s ON so.SO_NUMBER = s.SO_HEADER_REF
GROUP BY 1, 2;

-- 2. PROCUREMENT TEAM VIEW:
-- Measures Inbound OTD based on Supplier Portal Commit date vs Goods Receipt Date with a lenient +3 day grace window
CREATE OR REPLACE VIEW LEGACY.VW_PROCUREMENT_OTD AS
SELECT 
    DATE_TRUNC('month', TRY_TO_DATE(po.ORDER_DATE_STR, 'YYYY-MM-DD')) AS ORDER_MONTH,
    CASE 
        WHEN DATE_TRUNC('month', TRY_TO_DATE(po.ORDER_DATE_STR, 'YYYY-MM-DD')) BETWEEN '2026-07-01' AND '2026-09-30' THEN 'Q3 2026'
        ELSE 'OTHER'
    END AS QUARTER_LABEL,
    COUNT(gr.GR_LINE_ID) AS TOTAL_RECEIPTS,
    COUNT(CASE 
        WHEN TRY_TO_DATE(gr.RECEIPT_DATE_STR, 'YYYY-MM-DD') <= DATEADD('day', 3, TRY_TO_DATE(c.SUPPLIER_PROMISED_DATE, 'YYYY-MM-DD')) THEN 1 
    END) AS ON_TIME_GR_COUNT,
    ROUND(100.0 * COUNT(CASE 
        WHEN TRY_TO_DATE(gr.RECEIPT_DATE_STR, 'YYYY-MM-DD') <= DATEADD('day', 3, TRY_TO_DATE(c.SUPPLIER_PROMISED_DATE, 'YYYY-MM-DD')) THEN 1 
    END) / NULLIF(COUNT(gr.GR_LINE_ID), 0), 2) AS PROCUREMENT_INBOUND_OTD_PCT
FROM RAW.ERP_PURCHASE_ORDERS po
JOIN RAW.ERP_GOODS_RECEIPTS gr ON po.PO_LINE_ID = gr.PO_LINE_REF
JOIN RAW.SUPPLIER_PORTAL_COMMITS c ON po.PO_LINE_ID = c.PO_LINE_REF
WHERE gr.RECEIPT_DATE_STR IS NOT NULL
GROUP BY 1, 2;

-- 3. LOGISTICS TEAM VIEW:
-- Measures Outbound OTD strictly based on Customer Requested Date vs Final Proof-of-Delivery Timestamp (penalizes transit & late orders)
CREATE OR REPLACE VIEW LEGACY.VW_LOGISTICS_OTD AS
SELECT 
    DATE_TRUNC('month', TRY_TO_DATE(so.SO_DATE_STR, 'YYYY-MM-DD')) AS ORDER_MONTH,
    CASE 
        WHEN DATE_TRUNC('month', TRY_TO_DATE(so.SO_DATE_STR, 'YYYY-MM-DD')) BETWEEN '2026-07-01' AND '2026-09-30' THEN 'Q3 2026'
        ELSE 'OTHER'
    END AS QUARTER_LABEL,
    COUNT(s.SHIPMENT_NO) AS TOTAL_DELIVERIES,
    COUNT(CASE 
        WHEN TRY_TO_DATE(SUBSTRING(s.DELIVERY_TS_STR, 1, 10), 'YYYY-MM-DD') <= TRY_TO_DATE(so.REQ_DELIV_DATE_STR, 'YYYY-MM-DD') THEN 1 
    END) AS ON_TIME_DELIVERY_COUNT,
    ROUND(100.0 * COUNT(CASE 
        WHEN TRY_TO_DATE(SUBSTRING(s.DELIVERY_TS_STR, 1, 10), 'YYYY-MM-DD') <= TRY_TO_DATE(so.REQ_DELIV_DATE_STR, 'YYYY-MM-DD') THEN 1 
    END) / NULLIF(COUNT(s.SHIPMENT_NO), 0), 2) AS LOGISTICS_OUTBOUND_OTD_PCT
FROM RAW.ERP_SALES_ORDERS so
JOIN RAW.LOGISTICS_SHIPMENTS s ON so.SO_NUMBER = s.SO_HEADER_REF
WHERE s.STATUS = 'DELIVERED' AND s.DELIVERY_TS_STR IS NOT NULL
GROUP BY 1, 2;
