-- ==============================================================================
-- 05_curated_dynamic_tables.sql
-- Conformed Dimensional & Fact Dynamic Tables for Supply Chain Ontology
-- ==============================================================================

USE DATABASE SC_ONTOLOGY;
USE SCHEMA CURATED;
USE WAREHOUSE HACK_WH;

-- 1. Conformed Date Dimension (Base table: RAW.ERP_INVENTORY_SNAPSHOTS)
CREATE OR REPLACE DYNAMIC TABLE CURATED.DIM_DATE
    TARGET_LAG = '1 day'
    WAREHOUSE = HACK_WH
AS
SELECT 
    TO_NUMBER(TO_VARCHAR(d_date, 'YYYYMMDD')) AS DATE_KEY,
    d_date AS FULL_DATE,
    EXTRACT(year FROM d_date) AS YEAR,
    'Q' || EXTRACT(quarter FROM d_date) AS QUARTER,
    'Q' || EXTRACT(quarter FROM d_date) || ' ' || EXTRACT(year FROM d_date) AS QUARTER_YEAR,
    EXTRACT(month FROM d_date) AS MONTH_NUM,
    TO_VARCHAR(d_date, 'MMMM') AS MONTH_NAME,
    TO_VARCHAR(d_date, 'YYYY-MM') AS YEAR_MONTH,
    EXTRACT(week FROM d_date) AS WEEK_OF_YEAR,
    DAYNAME(d_date) AS DAY_NAME,
    CASE WHEN EXTRACT(dayofweek FROM d_date) IN (0, 6) THEN TRUE ELSE FALSE END AS IS_WEEKEND
FROM (
    SELECT DISTINCT COALESCE(TRY_TO_DATE(SNAP_DATE_STR, 'YYYY-MM-DD'), TRY_TO_DATE(SNAP_DATE_STR, 'DD/MM/YYYY')) AS d_date
    FROM RAW.ERP_INVENTORY_SNAPSHOTS
    WHERE SNAP_DATE_STR IS NOT NULL
);

-- 2. Conformed Plant Dimension
CREATE OR REPLACE DYNAMIC TABLE CURATED.DIM_PLANT
    TARGET_LAG = '1 day'
    WAREHOUSE = HACK_WH
AS
SELECT 
    HASH(PLANT_CODE) AS PLANT_KEY,
    PLANT_CODE,
    PLANT_NAME,
    CITY,
    COUNTRY_CODE AS COUNTRY,
    REGION,
    TZ_OFFSET AS TIMEZONE
FROM RAW.ERP_PLANTS;

-- 3. Conformed Supplier Dimension (Resolves 3 different IDs into canonical SUPPLIER_KEY)
CREATE OR REPLACE DYNAMIC TABLE CURATED.DIM_SUPPLIER
    TARGET_LAG = '1 day'
    WAREHOUSE = HACK_WH
AS
SELECT 
    HASH(VENDOR_ID) AS SUPPLIER_KEY,
    VENDOR_ID AS SUPPLIER_ID,
    VENDOR_NAME AS SUPPLIER_NAME,
    TIER_CODE AS SUPPLIER_TIER,
    COUNTRY,
    CASE 
        WHEN COUNTRY IN ('USA', 'Canada', 'Mexico') THEN 'AMER'
        WHEN COUNTRY IN ('Germany', 'United Kingdom', 'France') THEN 'EMEA'
        ELSE 'APAC'
    END AS REGION,
    STATUS_FLAG AS STATUS
FROM RAW.ERP_SUPPLIERS;

-- 4. Conformed Part Dimension (Standardized Standard Cost in USD)
CREATE OR REPLACE DYNAMIC TABLE CURATED.DIM_PART
    TARGET_LAG = '1 day'
    WAREHOUSE = HACK_WH
AS
SELECT 
    HASH(p.MATERIAL_NO) AS PART_KEY,
    p.MATERIAL_NO AS PART_NUMBER,
    p.DESCRIPTION AS PART_NAME,
    p.COMMODITY_GROUP AS PART_CATEGORY,
    p.BASE_UOM AS UNIT_OF_MEASURE,
    ROUND(p.STD_COST_LOCAL * COALESCE(fx.EXCHANGE_RATE, 1.000000), 2) AS STANDARD_COST_USD,
    CASE WHEN p.IS_CRITICAL_FLAG = 'Y' THEN TRUE ELSE FALSE END AS IS_CRITICAL
FROM RAW.ERP_PARTS p
LEFT JOIN RAW.FX_RATES fx 
    ON p.LOCAL_CURR = fx.BASE_CURRENCY 
   AND fx.YEAR_MONTH = '2025-10';

-- 5. Conformed Product Dimension
CREATE OR REPLACE DYNAMIC TABLE CURATED.DIM_PRODUCT
    TARGET_LAG = '1 day'
    WAREHOUSE = HACK_WH
AS
SELECT 
    HASH(MATNR_FG) AS PRODUCT_KEY,
    MATNR_FG AS PRODUCT_SKU,
    PRODUCT_NAME,
    PROD_FAMILY AS PRODUCT_FAMILY,
    LIST_PRICE_USD AS BASE_PRICE_USD
FROM RAW.ERP_PRODUCTS;

-- 6. Conformed Customer Dimension
CREATE OR REPLACE DYNAMIC TABLE CURATED.DIM_CUSTOMER
    TARGET_LAG = '1 day'
    WAREHOUSE = HACK_WH
AS
SELECT 
    HASH(KUNNR) AS CUSTOMER_KEY,
    KUNNR AS CUSTOMER_ID,
    NAME_ORG AS CUSTOMER_NAME,
    INDUSTRY_SECTOR AS CUSTOMER_SEGMENT,
    COUNTRY,
    REGION
FROM RAW.ERP_CUSTOMERS;

-- 7. Conformed Carrier Dimension
CREATE OR REPLACE DYNAMIC TABLE CURATED.DIM_CARRIER
    TARGET_LAG = '1 day'
    WAREHOUSE = HACK_WH
AS
SELECT 
    HASH(CARRIER_CODE) AS CARRIER_KEY,
    CARRIER_CODE,
    CARRIER_NAME,
    TRANSPORT_MODE,
    RELIABILITY_RATING
FROM RAW.LOGISTICS_CARRIERS;

-- 8. Conformed Bridge Bill of Materials (BOM)
CREATE OR REPLACE DYNAMIC TABLE CURATED.BRIDGE_BILL_OF_MATERIALS
    TARGET_LAG = '1 day'
    WAREHOUSE = HACK_WH
AS
SELECT 
    HASH(b.BOM_ID) AS BOM_KEY,
    HASH(b.PARENT_MATNR) AS PRODUCT_KEY,
    HASH(b.CHILD_MATNR) AS PART_KEY,
    b.PARENT_MATNR AS PRODUCT_SKU,
    b.CHILD_MATNR AS PART_NUMBER,
    b.COMPONENT_QTY,
    b.UOM,
    b.SCRAP_PCT AS SCRAP_FACTOR,
    TRUE AS IS_ACTIVE
FROM RAW.ERP_BILL_OF_MATERIALS b;

-- 9. Conformed Supplier Part SLA Dimension
CREATE OR REPLACE DYNAMIC TABLE CURATED.DIM_SUPPLIER_PART_SLA
    TARGET_LAG = '1 day'
    WAREHOUSE = HACK_WH
AS
SELECT 
    HASH(c.CONTRACT_ID || '-' || p.MATERIAL_NO) AS SLA_KEY,
    HASH(c.SUPPLIER_CODE) AS SUPPLIER_KEY,
    HASH(p.MATERIAL_NO) AS PART_KEY,
    HASH('VN-BD-03') AS PLANT_KEY,
    c.SUPPLIER_CODE,
    p.MATERIAL_NO AS PART_NUMBER,
    c.CONTRACT_LEAD_TIME_DAYS,
    c.TARGET_OTIF_PCT,
    ROUND(p.STD_COST_LOCAL * 0.95, 2) AS UNIT_PURCHASE_PRICE_USD,
    c.PENALTY_TERMS AS PENALTY_CLAUSE_TEXT,
    c.EFFECTIVE_DATE AS EFFECTIVE_START_DATE,
    c.EXPIRATION_DATE AS EFFECTIVE_END_DATE
FROM RAW.SUPPLIER_CONTRACTS c
CROSS JOIN (
    SELECT MATERIAL_NO, STD_COST_LOCAL 
    FROM RAW.ERP_PARTS 
    WHERE MATERIAL_NO IN ('PART-TF-88', 'PART-MC-02', 'PART-001', 'PART-003', 'PART-004')
) p;

-- 10. Conformed Sales Orders Header Fact
CREATE OR REPLACE DYNAMIC TABLE CURATED.FACT_SALES_ORDERS
    TARGET_LAG = '1 day'
    WAREHOUSE = HACK_WH
AS
SELECT 
    HASH(so.SO_NUMBER) AS SALES_ORDER_KEY,
    so.SO_NUMBER,
    HASH(so.CUST_ID) AS CUSTOMER_KEY,
    TO_NUMBER(TO_VARCHAR(COALESCE(TRY_TO_DATE(so.SO_DATE_STR, 'YYYY-MM-DD'), TRY_TO_DATE(so.SO_DATE_STR, 'DD/MM/YYYY')), 'YYYYMMDD')) AS ORDER_DATE_KEY,
    TO_NUMBER(TO_VARCHAR(COALESCE(TRY_TO_DATE(so.REQ_DELIV_DATE_STR, 'YYYY-MM-DD'), TRY_TO_DATE(so.REQ_DELIV_DATE_STR, 'DD/MM/YYYY')), 'YYYYMMDD')) AS REQUESTED_DELIVERY_DATE_KEY,
    TO_NUMBER(TO_VARCHAR(COALESCE(TRY_TO_DATE(so.PROMISED_DELIV_DATE_STR, 'YYYY-MM-DD'), TRY_TO_DATE(so.PROMISED_DELIV_DATE_STR, 'DD/MM/YYYY')), 'YYYYMMDD')) AS PROMISED_DELIVERY_DATE_KEY,
    so.HEADER_STATUS AS ORDER_STATUS,
    so.TOTAL_VAL_USD AS TOTAL_ORDER_AMOUNT_USD
FROM RAW.ERP_SALES_ORDERS so;

-- 11. Conformed Purchase Orders Fact (Extended Landed Cost & Inbound Flags)
CREATE OR REPLACE DYNAMIC TABLE CURATED.FACT_PURCHASE_ORDERS
    TARGET_LAG = '1 day'
    WAREHOUSE = HACK_WH
AS
SELECT 
    HASH(po.PO_LINE_ID) AS PO_LINE_KEY,
    po.PO_HEADER_NO AS PO_NUMBER,
    HASH(po.VENDOR_CODE) AS SUPPLIER_KEY,
    HASH(po.MATERIAL_NUM) AS PART_KEY,
    HASH(po.PLANT_CODE) AS PLANT_KEY,
    TO_NUMBER(TO_VARCHAR(COALESCE(TRY_TO_DATE(po.ORDER_DATE_STR, 'YYYY-MM-DD'), TRY_TO_DATE(po.ORDER_DATE_STR, 'DD/MM/YYYY')), 'YYYYMMDD')) AS ORDER_DATE_KEY,
    TO_NUMBER(TO_VARCHAR(COALESCE(TRY_TO_DATE(po.PROMISED_DATE_STR, 'YYYY-MM-DD'), TRY_TO_DATE(po.PROMISED_DATE_STR, 'DD/MM/YYYY')), 'YYYYMMDD')) AS PROMISED_DATE_KEY,
    TO_NUMBER(TO_VARCHAR(COALESCE(TRY_TO_DATE(gr.RECEIPT_DATE_STR, 'YYYY-MM-DD'), TRY_TO_DATE(gr.RECEIPT_DATE_STR, 'DD/MM/YYYY')), 'YYYYMMDD')) AS DELIVERY_DATE_KEY,
    COALESCE(TRY_TO_DATE(po.ORDER_DATE_STR, 'YYYY-MM-DD'), TRY_TO_DATE(po.ORDER_DATE_STR, 'DD/MM/YYYY')) AS ORDER_DATE,
    COALESCE(TRY_TO_DATE(po.PROMISED_DATE_STR, 'YYYY-MM-DD'), TRY_TO_DATE(po.PROMISED_DATE_STR, 'DD/MM/YYYY')) AS PROMISED_DATE,
    COALESCE(TRY_TO_DATE(gr.RECEIPT_DATE_STR, 'YYYY-MM-DD'), TRY_TO_DATE(gr.RECEIPT_DATE_STR, 'DD/MM/YYYY')) AS DELIVERY_DATE,
    po.ORDER_QTY,
    COALESCE(gr.QUANTITY_RCVD, 0.00) AS RECEIVED_QTY,
    ROUND(po.UNIT_COST_LOCAL * COALESCE(fx.EXCHANGE_RATE, 1.000000), 2) AS UNIT_PRICE_USD,
    ROUND(po.ORDER_QTY * (po.UNIT_COST_LOCAL * COALESCE(fx.EXCHANGE_RATE, 1.000000)), 2) AS EXTENDED_PURCHASE_COST_USD,
    ROUND(COALESCE(gr.INBOUND_FREIGHT_LOCAL, 0.00) * COALESCE(fx.EXCHANGE_RATE, 1.000000), 2) AS INBOUND_FREIGHT_USD,
    ROUND(COALESCE(gr.DUTY_COST_LOCAL, 0.00) * COALESCE(fx.EXCHANGE_RATE, 1.000000), 2) AS DUTY_COST_USD,
    ROUND(COALESCE(gr.HANDLING_COST_LOCAL, 0.00) * COALESCE(fx.EXCHANGE_RATE, 1.000000), 2) AS HANDLING_COST_USD,
    DATEDIFF('day', 
        COALESCE(TRY_TO_DATE(po.ORDER_DATE_STR, 'YYYY-MM-DD'), TRY_TO_DATE(po.ORDER_DATE_STR, 'DD/MM/YYYY')),
        COALESCE(TRY_TO_DATE(gr.RECEIPT_DATE_STR, 'YYYY-MM-DD'), TRY_TO_DATE(gr.RECEIPT_DATE_STR, 'DD/MM/YYYY'))
    ) AS LEAD_TIME_ACTUAL_DAYS,
    COALESCE(sla.CONTRACT_LEAD_TIME_DAYS, 14) AS LEAD_TIME_CONTRACT_DAYS,
    CASE WHEN gr.RECEIPT_DATE_STR IS NOT NULL THEN TRUE ELSE FALSE END AS IS_DELIVERED,
    CASE 
        WHEN gr.RECEIPT_DATE_STR IS NOT NULL 
         AND COALESCE(TRY_TO_DATE(gr.RECEIPT_DATE_STR, 'YYYY-MM-DD'), TRY_TO_DATE(gr.RECEIPT_DATE_STR, 'DD/MM/YYYY')) <= COALESCE(TRY_TO_DATE(po.PROMISED_DATE_STR, 'YYYY-MM-DD'), TRY_TO_DATE(po.PROMISED_DATE_STR, 'DD/MM/YYYY')) 
        THEN TRUE ELSE FALSE 
    END AS IS_ON_TIME_INBOUND,
    CASE 
        WHEN gr.RECEIPT_DATE_STR IS NOT NULL AND gr.QUANTITY_RCVD >= po.ORDER_QTY THEN TRUE ELSE FALSE 
    END AS IS_IN_FULL_INBOUND
FROM RAW.ERP_PURCHASE_ORDERS po
LEFT JOIN RAW.ERP_GOODS_RECEIPTS gr ON po.PO_LINE_ID = gr.PO_LINE_REF
LEFT JOIN RAW.FX_RATES fx 
    ON po.CURR_CODE = fx.BASE_CURRENCY 
   AND fx.YEAR_MONTH = SUBSTRING(po.ORDER_DATE_STR, 1, 7)
LEFT JOIN RAW.SUPPLIER_CONTRACTS sla ON po.VENDOR_CODE = sla.SUPPLIER_CODE;

-- 12. Conformed Outbound Shipments Fact
CREATE OR REPLACE DYNAMIC TABLE CURATED.FACT_OUTBOUND_SHIPMENTS
    TARGET_LAG = '1 day'
    WAREHOUSE = HACK_WH
AS
SELECT 
    HASH(sl.SHIP_LINE_ID) AS SHIPMENT_LINE_KEY,
    s.SHIPMENT_NO AS SHIPMENT_NUMBER,
    HASH(so.SO_NUMBER) AS SALES_ORDER_KEY,
    HASH(so.CUST_ID) AS CUSTOMER_KEY,
    HASH(s.ORIGIN_PLANT) AS PLANT_KEY,
    HASH(sl.PRODUCT_ID) AS PRODUCT_KEY,
    HASH(s.CARRIER_ID) AS CARRIER_KEY,
    TO_NUMBER(TO_VARCHAR(COALESCE(TRY_TO_DATE(so.SO_DATE_STR, 'YYYY-MM-DD'), TRY_TO_DATE(so.SO_DATE_STR, 'DD/MM/YYYY')), 'YYYYMMDD')) AS ORDER_DATE_KEY,
    TO_NUMBER(TO_VARCHAR(COALESCE(TRY_TO_DATE(so.PROMISED_DELIV_DATE_STR, 'YYYY-MM-DD'), TRY_TO_DATE(so.PROMISED_DELIV_DATE_STR, 'DD/MM/YYYY')), 'YYYYMMDD')) AS PROMISED_DELIVERY_DATE_KEY,
    TO_NUMBER(TO_VARCHAR(COALESCE(TRY_TO_DATE(SUBSTRING(s.DELIVERY_TS_STR, 1, 10), 'YYYY-MM-DD'), TRY_TO_DATE(SUBSTRING(s.DELIVERY_TS_STR, 1, 10), 'DD/MM/YYYY')), 'YYYYMMDD')) AS ACTUAL_DELIVERY_DATE_KEY,
    COALESCE(TRY_TO_DATE(so.SO_DATE_STR, 'YYYY-MM-DD'), TRY_TO_DATE(so.SO_DATE_STR, 'DD/MM/YYYY')) AS ORDER_DATE,
    COALESCE(TRY_TO_DATE(so.PROMISED_DELIV_DATE_STR, 'YYYY-MM-DD'), TRY_TO_DATE(so.PROMISED_DELIV_DATE_STR, 'DD/MM/YYYY')) AS PROMISED_DELIVERY_DATE,
    COALESCE(TRY_TO_DATE(SUBSTRING(s.DELIVERY_TS_STR, 1, 10), 'YYYY-MM-DD'), TRY_TO_DATE(SUBSTRING(s.DELIVERY_TS_STR, 1, 10), 'DD/MM/YYYY')) AS ACTUAL_DELIVERY_DATE,
    sol.ORDER_QTY AS ORDERED_QTY,
    sl.QTY_SHIPPED,
    sl.QTY_DELIVERED,
    ROUND(s.FREIGHT_CHARGE_USD / 3.0, 2) AS FREIGHT_COST_USD,
    ROUND(s.HANDLING_CHARGE_USD / 3.0, 2) AS HANDLING_COST_USD,
    CASE WHEN s.STATUS = 'DELIVERED' AND s.DELIVERY_TS_STR IS NOT NULL THEN TRUE ELSE FALSE END AS IS_DELIVERED,
    CASE 
        WHEN s.STATUS = 'DELIVERED' 
         AND s.DELIVERY_TS_STR IS NOT NULL 
         AND COALESCE(TRY_TO_DATE(SUBSTRING(s.DELIVERY_TS_STR, 1, 10), 'YYYY-MM-DD'), TRY_TO_DATE(SUBSTRING(s.DELIVERY_TS_STR, 1, 10), 'DD/MM/YYYY')) <= COALESCE(TRY_TO_DATE(so.PROMISED_DELIV_DATE_STR, 'YYYY-MM-DD'), TRY_TO_DATE(so.PROMISED_DELIV_DATE_STR, 'DD/MM/YYYY'))
        THEN TRUE ELSE FALSE 
    END AS IS_ON_TIME_OUTBOUND,
    CASE 
        WHEN s.STATUS = 'DELIVERED' 
         AND sl.QTY_DELIVERED >= sol.ORDER_QTY 
        THEN TRUE ELSE FALSE 
    END AS IS_IN_FULL_OUTBOUND,
    CASE WHEN s.IS_BACKORDERED_FLAG = 'Y' THEN TRUE ELSE FALSE END AS IS_BACKORDERED
FROM RAW.LOGISTICS_SHIPMENTS s
JOIN RAW.LOGISTICS_SHIPMENT_LINES sl ON s.SHIPMENT_NO = sl.SHIPMENT_NO
JOIN RAW.ERP_SALES_ORDERS so ON s.SO_HEADER_REF = so.SO_NUMBER
JOIN RAW.ERP_SALES_ORDER_LINES sol ON sl.SO_LINE_REF = sol.SO_LINE_ID;

-- 13. Conformed Daily Inventory Snapshots Fact
CREATE OR REPLACE DYNAMIC TABLE CURATED.FACT_INVENTORY_DAILY
    TARGET_LAG = '1 day'
    WAREHOUSE = HACK_WH
AS
SELECT 
    HASH(inv.INV_SNAP_ID) AS INV_SNAPSHOT_KEY,
    TO_NUMBER(TO_VARCHAR(COALESCE(TRY_TO_DATE(inv.SNAP_DATE_STR, 'YYYY-MM-DD'), TRY_TO_DATE(inv.SNAP_DATE_STR, 'DD/MM/YYYY')), 'YYYYMMDD')) AS SNAPSHOT_DATE_KEY,
    COALESCE(TRY_TO_DATE(inv.SNAP_DATE_STR, 'YYYY-MM-DD'), TRY_TO_DATE(inv.SNAP_DATE_STR, 'DD/MM/YYYY')) AS SNAPSHOT_DATE,
    HASH(inv.PLANT_CODE) AS PLANT_KEY,
    HASH(inv.MATERIAL_NO) AS PART_KEY,
    inv.PLANT_CODE,
    inv.MATERIAL_NO AS PART_NUMBER,
    inv.STOCK_ON_HAND AS ON_HAND_QTY,
    inv.SAFETY_STOCK_MIN AS SAFETY_STOCK_QTY,
    inv.DAILY_USAGE_30D AS DAILY_CONSUMPTION_QTY,
    ROUND(inv.STOCK_ON_HAND * p.STANDARD_COST_USD, 2) AS INVENTORY_VALUE_USD
FROM RAW.ERP_INVENTORY_SNAPSHOTS inv
JOIN CURATED.DIM_PART p ON HASH(inv.MATERIAL_NO) = p.PART_KEY;

-- 14. Current Inventory Position & DOI Dynamic Table
CREATE OR REPLACE DYNAMIC TABLE CURATED.INVENTORY_POSITION_CURRENT
    TARGET_LAG = '1 day'
    WAREHOUSE = HACK_WH
AS
WITH latest_inv AS (
    SELECT 
        plant_key,
        part_key,
        plant_code,
        part_number,
        on_hand_qty,
        safety_stock_qty,
        inventory_value_usd,
        snapshot_date
    FROM CURATED.FACT_INVENTORY_DAILY
    QUALIFY ROW_NUMBER() OVER (PARTITION BY plant_key, part_key ORDER BY snapshot_date DESC) = 1
),
trailing_consumption AS (
    SELECT 
        plant_key,
        part_key,
        AVG(daily_consumption_qty) AS avg_daily_consumption_30d
    FROM CURATED.FACT_INVENTORY_DAILY
    WHERE snapshot_date >= '2026-09-01'::DATE
    GROUP BY plant_key, part_key
)
SELECT 
    HASH(l.plant_code || '-' || l.part_number) AS INV_POSITION_KEY,
    l.plant_key,
    l.part_key,
    l.plant_code,
    l.part_number,
    l.snapshot_date AS AS_OF_DATE,
    l.on_hand_qty,
    l.safety_stock_qty,
    l.inventory_value_usd,
    c.avg_daily_consumption_30d,
    ROUND(l.on_hand_qty / NULLIF(c.avg_daily_consumption_30d, 0), 1) AS DAYS_OF_INVENTORY,
    CASE 
        WHEN l.on_hand_qty = 0 THEN 'STOCKOUT'
        WHEN l.on_hand_qty < l.safety_stock_qty THEN 'CRITICAL_LOW'
        WHEN l.on_hand_qty / NULLIF(c.avg_daily_consumption_30d, 0) > 45 THEN 'EXCESS'
        ELSE 'OPTIMAL'
    END AS INVENTORY_HEALTH_STATUS
FROM latest_inv l
JOIN trailing_consumption c ON l.plant_key = c.plant_key AND l.part_key = c.part_key;
