-- ==============================================================================
-- 06_streams_tasks.sql
-- Stream, Scheduled Tasks, and Action Tracking for Supply Chain Ontology
-- ==============================================================================

USE DATABASE SC_ONTOLOGY;
USE SCHEMA APP;
USE WAREHOUSE HACK_WH;

-- 1. APP.ACTIONS Table (Action Tickets & Escalation Log)
CREATE OR REPLACE TABLE APP.ACTIONS (
    ACTION_ID VARCHAR(50) PRIMARY KEY,
    ACTION_TYPE VARCHAR(50),          -- IOT_ALERT, SUPPLIER_ESCALATION, INVENTORY_REORDER, CARRIER_REVIEW
    TARGET_ENTITY_TYPE VARCHAR(50),   -- SHIPMENT, SUPPLIER, PART, CARRIER
    TARGET_ENTITY_ID VARCHAR(50),     -- E.g. SHP-00104, SUP-104, PART-MC-02
    SEVERITY VARCHAR(20),             -- LOW, MEDIUM, HIGH, CRITICAL
    DESCRIPTION VARCHAR(1000),
    STATUS VARCHAR(50) DEFAULT 'OPEN_PENDING_REVIEW',
    CREATED_BY VARCHAR(100) DEFAULT 'CORTEX_AGENT',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 2. APP.CONSISTENCY_LOG Table (Automated Metric Consistency Audit Log)
CREATE OR REPLACE TABLE APP.CONSISTENCY_LOG (
    LOG_ID VARCHAR(50) PRIMARY KEY,
    CHECK_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    METRIC_NAME VARCHAR(100),
    LEGACY_PLANNING_VAL NUMBER(6,2),
    LEGACY_PROCUREMENT_VAL NUMBER(6,2),
    LEGACY_LOGISTICS_VAL NUMBER(6,2),
    CURATED_CANONICAL_VAL NUMBER(6,2),
    DELTA_MAX NUMBER(6,2),
    STATUS VARCHAR(50)
);

-- 3. Stored Procedure for Cortex Agent Custom Tool: Action Creation
CREATE OR REPLACE PROCEDURE APP.SP_CREATE_ACTION_ITEM(
    P_ACTION_TYPE VARCHAR,
    P_TARGET_ENTITY_TYPE VARCHAR,
    P_TARGET_ENTITY_ID VARCHAR,
    P_SEVERITY VARCHAR,
    P_DESCRIPTION VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    V_ACTION_ID VARCHAR;
BEGIN
    V_ACTION_ID := 'ACT-' || TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD-HH24MISS') || '-' || SUBSTRING(UUID_STRING(), 1, 4);
    
    INSERT INTO APP.ACTIONS (
        ACTION_ID, ACTION_TYPE, TARGET_ENTITY_TYPE, TARGET_ENTITY_ID, 
        SEVERITY, DESCRIPTION, STATUS, CREATED_BY, CREATED_AT
    ) VALUES (
        :V_ACTION_ID, :P_ACTION_TYPE, :P_TARGET_ENTITY_TYPE, :P_TARGET_ENTITY_ID,
        :P_SEVERITY, :P_DESCRIPTION, 'OPEN_PENDING_REVIEW', 'CORTEX_AGENT_USER', CURRENT_TIMESTAMP()
    );
    
    RETURN 'SUCCESS: Created Action Item ' || :V_ACTION_ID || ' with Severity ' || :P_SEVERITY;
END;
$$;

-- 4. Stored Procedure for Automated Daily Consistency Audit
CREATE OR REPLACE PROCEDURE APP.SP_RUN_METRIC_CONSISTENCY_CHECK()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    V_PLANNING_OTD NUMBER(6,2);
    V_PROCUREMENT_OTD NUMBER(6,2);
    V_LOGISTICS_OTD NUMBER(6,2);
    V_CANONICAL_OTD NUMBER(6,2);
    V_MAX_DELTA NUMBER(6,2);
    V_LOG_ID VARCHAR;
BEGIN
    -- Query Legacy Planning OTD for Q3 2026
    SELECT ROUND(100.0 * SUM(ON_TIME_DISPATCH_COUNT) / NULLIF(SUM(TOTAL_SHIPMENTS), 0), 2)
    INTO :V_PLANNING_OTD
    FROM LEGACY.VW_PLANNING_OTD
    WHERE QUARTER_LABEL = 'Q3 2026';

    -- Query Legacy Procurement Inbound OTD for Q3 2026
    SELECT ROUND(100.0 * SUM(ON_TIME_GR_COUNT) / NULLIF(SUM(TOTAL_RECEIPTS), 0), 2)
    INTO :V_PROCUREMENT_OTD
    FROM LEGACY.VW_PROCUREMENT_OTD
    WHERE QUARTER_LABEL = 'Q3 2026';

    -- Query Legacy Logistics Outbound OTD for Q3 2026
    SELECT ROUND(100.0 * SUM(ON_TIME_DELIVERY_COUNT) / NULLIF(SUM(TOTAL_DELIVERIES), 0), 2)
    INTO :V_LOGISTICS_OTD
    FROM LEGACY.VW_LOGISTICS_OTD
    WHERE QUARTER_LABEL = 'Q3 2026';

    -- Query Curated Canonical Outbound OTD for Q3 2026
    SELECT ROUND(100.0 * COUNT(CASE WHEN IS_ON_TIME_OUTBOUND = TRUE THEN 1 END) / NULLIF(COUNT(CASE WHEN IS_DELIVERED = TRUE THEN 1 END), 0), 2)
    INTO :V_CANONICAL_OTD
    FROM CURATED.FACT_OUTBOUND_SHIPMENTS
    WHERE ORDER_DATE BETWEEN '2026-07-01' AND '2026-09-30';

    -- Compute maximum delta between conflicting views
    V_MAX_DELTA := GREATEST(
        ABS(COALESCE(:V_PLANNING_OTD, 0) - COALESCE(:V_CANONICAL_OTD, 0)),
        ABS(COALESCE(:V_PROCUREMENT_OTD, 0) - COALESCE(:V_CANONICAL_OTD, 0)),
        ABS(COALESCE(:V_LOGISTICS_OTD, 0) - COALESCE(:V_CANONICAL_OTD, 0))
    );

    V_LOG_ID := 'CHK-' || TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD-HH24MISS');

    INSERT INTO APP.CONSISTENCY_LOG (
        LOG_ID, CHECK_TIMESTAMP, METRIC_NAME, 
        LEGACY_PLANNING_VAL, LEGACY_PROCUREMENT_VAL, LEGACY_LOGISTICS_VAL, 
        CURATED_CANONICAL_VAL, DELTA_MAX, STATUS
    ) VALUES (
        :V_LOG_ID, CURRENT_TIMESTAMP(), 'Outbound_OTD_Q3_2026',
        :V_PLANNING_OTD, :V_PROCUREMENT_OTD, :V_LOGISTICS_OTD,
        :V_CANONICAL_OTD, :V_MAX_DELTA, 'AUDITED_DIVERGENCE_CONFIRMED'
    );

    RETURN 'SUCCESS: Audited Q3 2026 OTD. Legacy Planning=' || COALESCE(:V_PLANNING_OTD,0) || '%, Legacy Proc=' || COALESCE(:V_PROCUREMENT_OTD,0) || '%, Legacy Log=' || COALESCE(:V_LOGISTICS_OTD,0) || '%, Curated Canonical=' || COALESCE(:V_CANONICAL_OTD,0) || '%. Logged to ' || :V_LOG_ID;
END;
$$;

-- 5. Stream on RAW IoT Telemetry
CREATE OR REPLACE STREAM RAW.STM_IOT_TELEMETRY ON TABLE RAW.IOT_TELEMETRY;

-- 6. Task: IoT Telemetry Anomaly Watchdog (Schedule: 60 MINUTE, condition-gated)
CREATE OR REPLACE TASK APP.TSK_ANOMALY_WATCHDOG
    WAREHOUSE = HACK_WH
    SCHEDULE = '60 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('RAW.STM_IOT_TELEMETRY')
AS
INSERT INTO APP.ACTIONS (
    ACTION_ID, ACTION_TYPE, TARGET_ENTITY_TYPE, TARGET_ENTITY_ID, 
    SEVERITY, DESCRIPTION, STATUS, CREATED_BY, CREATED_AT
)
SELECT 
    'IOT-' || s.EVENT_ID,
    'IOT_ALERT',
    'SHIPMENT',
    s.SHIPMENT_NO,
    CASE WHEN s.TEMPERATURE_C > 28.0 OR s.SHOCK_G > 6.0 THEN 'CRITICAL' ELSE 'HIGH' END,
    'Telemetry Excursion Detected: Temp=' || s.TEMPERATURE_C || '°C, Shock=' || s.SHOCK_G || 'G at Device ' || s.DEVICE_ID,
    'OPEN_PENDING_REVIEW',
    'APP.TSK_ANOMALY_WATCHDOG',
    CURRENT_TIMESTAMP()
FROM RAW.STM_IOT_TELEMETRY s
WHERE (s.TEMPERATURE_C > 25.0 OR s.SHOCK_G > 5.0)
  AND s.METADATA$ACTION = 'INSERT';

-- 7. Task: Daily Metric Consistency Audit Test Task (Schedule: 1440 MINUTE)
CREATE OR REPLACE TASK APP.TSK_DAILY_METRIC_CONSISTENCY_TEST
    WAREHOUSE = HACK_WH
    SCHEDULE = '1440 MINUTE'
AS
CALL APP.SP_RUN_METRIC_CONSISTENCY_CHECK();
