-- ==============================================================================
-- 07_quality_checks.sql
-- Automated Data Quality & Referential Integrity Assertions for Curated Layer
-- ==============================================================================

USE DATABASE SC_ONTOLOGY;
USE SCHEMA CURATED;
USE WAREHOUSE HACK_WH;

-- 1. Compare RAW vs CURATED Row Counts
SELECT 'DIM_PLANT' AS OBJECT_NAME, (SELECT COUNT(*) FROM RAW.ERP_PLANTS) AS RAW_COUNT, (SELECT COUNT(*) FROM CURATED.DIM_PLANT) AS CURATED_COUNT
UNION ALL
SELECT 'DIM_SUPPLIER', (SELECT COUNT(*) FROM RAW.ERP_SUPPLIERS), (SELECT COUNT(*) FROM CURATED.DIM_SUPPLIER)
UNION ALL
SELECT 'DIM_PART', (SELECT COUNT(*) FROM RAW.ERP_PARTS), (SELECT COUNT(*) FROM CURATED.DIM_PART)
UNION ALL
SELECT 'DIM_PRODUCT', (SELECT COUNT(*) FROM RAW.ERP_PRODUCTS), (SELECT COUNT(*) FROM CURATED.DIM_PRODUCT)
UNION ALL
SELECT 'DIM_CUSTOMER', (SELECT COUNT(*) FROM RAW.ERP_CUSTOMERS), (SELECT COUNT(*) FROM CURATED.DIM_CUSTOMER)
UNION ALL
SELECT 'DIM_CARRIER', (SELECT COUNT(*) FROM RAW.LOGISTICS_CARRIERS), (SELECT COUNT(*) FROM CURATED.DIM_CARRIER)
UNION ALL
SELECT 'BRIDGE_BILL_OF_MATERIALS', (SELECT COUNT(*) FROM RAW.ERP_BILL_OF_MATERIALS), (SELECT COUNT(*) FROM CURATED.BRIDGE_BILL_OF_MATERIALS)
UNION ALL
SELECT 'FACT_SALES_ORDERS', (SELECT COUNT(*) FROM RAW.ERP_SALES_ORDERS), (SELECT COUNT(*) FROM CURATED.FACT_SALES_ORDERS)
UNION ALL
SELECT 'FACT_PURCHASE_ORDERS', (SELECT COUNT(*) FROM RAW.ERP_PURCHASE_ORDERS), (SELECT COUNT(*) FROM CURATED.FACT_PURCHASE_ORDERS)
UNION ALL
SELECT 'FACT_OUTBOUND_SHIPMENTS', (SELECT COUNT(*) FROM RAW.LOGISTICS_SHIPMENT_LINES), (SELECT COUNT(*) FROM CURATED.FACT_OUTBOUND_SHIPMENTS)
UNION ALL
SELECT 'FACT_INVENTORY_DAILY', (SELECT COUNT(*) FROM RAW.ERP_INVENTORY_SNAPSHOTS), (SELECT COUNT(*) FROM CURATED.FACT_INVENTORY_DAILY)
ORDER BY OBJECT_NAME;

-- 2. Check for NULL Primary or Surrogate Keys (Must be 0)
SELECT 'FACT_OUTBOUND_SHIPMENTS NULL Keys' AS CHECK_NAME, COUNT(*) AS VIOLATION_COUNT
FROM CURATED.FACT_OUTBOUND_SHIPMENTS
WHERE SHIPMENT_LINE_KEY IS NULL 
   OR CUSTOMER_KEY IS NULL 
   OR PLANT_KEY IS NULL 
   OR PRODUCT_KEY IS NULL 
   OR CARRIER_KEY IS NULL 
   OR ORDER_DATE_KEY IS NULL

UNION ALL

SELECT 'FACT_PURCHASE_ORDERS NULL Keys', COUNT(*)
FROM CURATED.FACT_PURCHASE_ORDERS
WHERE PO_LINE_KEY IS NULL 
   OR SUPPLIER_KEY IS NULL 
   OR PART_KEY IS NULL 
   OR PLANT_KEY IS NULL 
   OR ORDER_DATE_KEY IS NULL

UNION ALL

SELECT 'FACT_INVENTORY_DAILY NULL Keys', COUNT(*)
FROM CURATED.FACT_INVENTORY_DAILY
WHERE INV_SNAPSHOT_KEY IS NULL 
   OR PLANT_KEY IS NULL 
   OR PART_KEY IS NULL 
   OR SNAPSHOT_DATE_KEY IS NULL;

-- 3. Check for Orphan Foreign Keys (Must be 0)
SELECT 'Orphan Customer Keys in Outbound Shipments' AS CHECK_NAME, COUNT(*) AS ORPHAN_COUNT
FROM CURATED.FACT_OUTBOUND_SHIPMENTS f
LEFT JOIN CURATED.DIM_CUSTOMER d ON f.CUSTOMER_KEY = d.CUSTOMER_KEY
WHERE d.CUSTOMER_KEY IS NULL

UNION ALL

SELECT 'Orphan Product Keys in Outbound Shipments', COUNT(*)
FROM CURATED.FACT_OUTBOUND_SHIPMENTS f
LEFT JOIN CURATED.DIM_PRODUCT d ON f.PRODUCT_KEY = d.PRODUCT_KEY
WHERE d.PRODUCT_KEY IS NULL

UNION ALL

SELECT 'Orphan Carrier Keys in Outbound Shipments', COUNT(*)
FROM CURATED.FACT_OUTBOUND_SHIPMENTS f
LEFT JOIN CURATED.DIM_CARRIER d ON f.CARRIER_KEY = d.CARRIER_KEY
WHERE d.CARRIER_KEY IS NULL

UNION ALL

SELECT 'Orphan Supplier Keys in Purchase Orders', COUNT(*)
FROM CURATED.FACT_PURCHASE_ORDERS f
LEFT JOIN CURATED.DIM_SUPPLIER d ON f.SUPPLIER_KEY = d.SUPPLIER_KEY
WHERE d.SUPPLIER_KEY IS NULL

UNION ALL

SELECT 'Orphan Part Keys in Purchase Orders', COUNT(*)
FROM CURATED.FACT_PURCHASE_ORDERS f
LEFT JOIN CURATED.DIM_PART d ON f.PART_KEY = d.PART_KEY
WHERE d.PART_KEY IS NULL

UNION ALL

SELECT 'Orphan Plant Keys in Purchase Orders', COUNT(*)
FROM CURATED.FACT_PURCHASE_ORDERS f
LEFT JOIN CURATED.DIM_PLANT d ON f.PLANT_KEY = d.PLANT_KEY
WHERE d.PLANT_KEY IS NULL;

-- 4. Check for Unmapped Vendor IDs & Unparsed Dates (Must be 0)
SELECT 'Unmapped Vendor IDs in POs' AS CHECK_NAME, COUNT(*) AS ERROR_COUNT
FROM CURATED.FACT_PURCHASE_ORDERS
WHERE SUPPLIER_KEY NOT IN (SELECT SUPPLIER_KEY FROM CURATED.DIM_SUPPLIER)

UNION ALL

SELECT 'Unparsed Dates in POs', COUNT(*)
FROM CURATED.FACT_PURCHASE_ORDERS
WHERE ORDER_DATE IS NULL OR PROMISED_DATE IS NULL

UNION ALL

SELECT 'Unparsed Dates in Shipments', COUNT(*)
FROM CURATED.FACT_OUTBOUND_SHIPMENTS
WHERE ORDER_DATE IS NULL OR PROMISED_DELIVERY_DATE IS NULL;
