-- ==============================================================================
-- 17_trust_layer.sql
-- Trust Layer: Data Freshness & Deterministic Metric Provenance
-- ==============================================================================

USE DATABASE SC_ONTOLOGY;
USE SCHEMA GOVERNANCE;
USE WAREHOUSE HACK_WH;

-- 1. Cheap Read-Only View of Curated Data Freshness
CREATE OR REPLACE VIEW GOVERNANCE.V_DATA_FRESHNESS 
COMMENT = 'Read-only metadata reporting row count, storage footprint, and last refresh timestamp for Curated entities'
AS
WITH table_meta AS (
    SELECT 
        TABLE_NAME,
        COALESCE(ROW_COUNT, 0) AS ROW_COUNT,
        COALESCE(BYTES, 0) AS BYTES,
        LAST_ALTERED AS LAST_REFRESH_TIME
    FROM SC_ONTOLOGY.INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'CURATED'
),
table_dates AS (
    SELECT 'FACT_OUTBOUND_SHIPMENTS' AS TABLE_NAME, MAX(COALESCE(ACTUAL_DELIVERY_DATE, ORDER_DATE)) AS LATEST_DATA_DATE FROM SC_ONTOLOGY.CURATED.FACT_OUTBOUND_SHIPMENTS
    UNION ALL
    SELECT 'FACT_PURCHASE_ORDERS', MAX(COALESCE(DELIVERY_DATE, ORDER_DATE)) FROM SC_ONTOLOGY.CURATED.FACT_PURCHASE_ORDERS
    UNION ALL
    SELECT 'FACT_SALES_ORDERS', (SELECT MAX(ORDER_DATE) FROM SC_ONTOLOGY.CURATED.FACT_OUTBOUND_SHIPMENTS)
    UNION ALL
    SELECT 'FACT_INVENTORY_DAILY', MAX(SNAPSHOT_DATE) FROM SC_ONTOLOGY.CURATED.FACT_INVENTORY_DAILY
    UNION ALL
    SELECT 'INVENTORY_POSITION_CURRENT', MAX(AS_OF_DATE) FROM SC_ONTOLOGY.CURATED.INVENTORY_POSITION_CURRENT
    UNION ALL
    SELECT 'DIM_DATE', MAX(FULL_DATE) FROM SC_ONTOLOGY.CURATED.DIM_DATE
    UNION ALL
    SELECT 'DIM_PLANT', CURRENT_DATE()
    UNION ALL
    SELECT 'DIM_SUPPLIER', CURRENT_DATE()
    UNION ALL
    SELECT 'DIM_PART', CURRENT_DATE()
    UNION ALL
    SELECT 'DIM_PRODUCT', CURRENT_DATE()
    UNION ALL
    SELECT 'DIM_CUSTOMER', CURRENT_DATE()
    UNION ALL
    SELECT 'DIM_CARRIER', CURRENT_DATE()
    UNION ALL
    SELECT 'BRIDGE_BILL_OF_MATERIALS', CURRENT_DATE()
    UNION ALL
    SELECT 'DIM_SUPPLIER_PART_SLA', CURRENT_DATE()
)
SELECT 
    m.TABLE_NAME,
    'CURATED.' || m.TABLE_NAME AS FULL_TABLE_NAME,
    m.ROW_COUNT,
    ROUND(m.BYTES / 1024.0, 2) AS SIZE_KB,
    m.LAST_REFRESH_TIME,
    d.LATEST_DATA_DATE
FROM table_meta m
LEFT JOIN table_dates d ON m.TABLE_NAME = d.TABLE_NAME;

-- 2. Deterministic Metric Provenance Table Function
-- Confidence Tier Rule:
-- 'Verified': Metric is formally registered and mapped to an AI Verified Query Reference (VQR) in Semantic View.
-- 'Governed/Ad-hoc': Metric is formally registered with an exact formula in METRIC_REGISTRY, calculated on conformed curated dynamic tables.
-- 'Unverified': Metric is not present in METRIC_REGISTRY.
CREATE OR REPLACE FUNCTION GOVERNANCE.F_METRIC_PROVENANCE(P_METRIC_NAME VARCHAR)
RETURNS TABLE (
    METRIC_KEY VARCHAR,
    METRIC_NAME VARCHAR,
    BUSINESS_DEFINITION VARCHAR,
    EXACT_SQL_FORMULA VARCHAR,
    GRAIN VARCHAR,
    OWNER_TEAM VARCHAR,
    VERIFIED_QUERY_REF VARCHAR,
    CONFIDENCE_TIER VARCHAR,
    PRIMARY_SOURCE_TABLE VARCHAR,
    PRIMARY_SOURCE_ROW_COUNT NUMBER,
    PRIMARY_SOURCE_LAST_REFRESH TIMESTAMP_LTZ(3),
    PRIMARY_SOURCE_DATA_DATE DATE,
    DEFINITION_VERSION NUMBER,
    APPROVED_BY VARCHAR
)
AS
$$
SELECT 
    r.METRIC_KEY,
    r.METRIC_NAME,
    r.BUSINESS_DEFINITION,
    r.EXACT_SQL_FORMULA,
    r.GRAIN,
    r.OWNER_TEAM,
    r.VERIFIED_QUERY_REF,
    CASE 
        WHEN r.VERIFIED_QUERY_REF IS NOT NULL THEN 'Verified'
        WHEN r.METRIC_KEY IS NOT NULL THEN 'Governed/Ad-hoc'
        ELSE 'Unverified'
    END AS CONFIDENCE_TIER,
    r.SOURCE_TABLES[0]::VARCHAR AS PRIMARY_SOURCE_TABLE,
    f.ROW_COUNT AS PRIMARY_SOURCE_ROW_COUNT,
    f.LAST_REFRESH_TIME AS PRIMARY_SOURCE_LAST_REFRESH,
    f.LATEST_DATA_DATE AS PRIMARY_SOURCE_DATA_DATE,
    r.DEFINITION_VERSION,
    r.APPROVED_BY
FROM GOVERNANCE.METRIC_REGISTRY r
LEFT JOIN GOVERNANCE.V_DATA_FRESHNESS f 
    ON f.FULL_TABLE_NAME = r.SOURCE_TABLES[0]::VARCHAR
WHERE LOWER(r.METRIC_NAME) = LOWER(P_METRIC_NAME)
   OR LOWER(r.METRIC_KEY) = LOWER(P_METRIC_NAME)
$$;
