-- ==============================================================================
-- 18_drift_sentinel.sql
-- Living Consistency Monitor & Drift Sentinel (Reusing APP.CONSISTENCY_LOG)
-- ==============================================================================

USE DATABASE SC_ONTOLOGY;
USE SCHEMA GOVERNANCE;
USE WAREHOUSE HACK_WH;

-- 1. Drift Check Stored Procedure
CREATE OR REPLACE PROCEDURE GOVERNANCE.SP_RUN_DRIFT_CHECK()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    V_PLANNING_OTD NUMBER(6,2);
    V_PROCUREMENT_OTD NUMBER(6,2);
    V_LOGISTICS_OTD NUMBER(6,2);
    V_CANONICAL_OTD NUMBER(6,2);
    V_MAX_DELTA NUMBER(6,2);
    V_LOG_ID VARCHAR;
    V_STATUS VARCHAR(50);
BEGIN
    -- 1. Legacy Planning OTD (Q3 2026: Sums on-time dispatch vs total shipments)
    SELECT ROUND(100.0 * SUM(ON_TIME_DISPATCH_COUNT) / NULLIF(SUM(TOTAL_SHIPMENTS), 0), 2)
    INTO :V_PLANNING_OTD
    FROM SC_ONTOLOGY.LEGACY.VW_PLANNING_OTD
    WHERE QUARTER_LABEL = 'Q3 2026';

    -- 2. Legacy Procurement Inbound OTD (Q3 2026: Sums on-time goods receipts vs total receipts)
    SELECT ROUND(100.0 * SUM(ON_TIME_GR_COUNT) / NULLIF(SUM(TOTAL_RECEIPTS), 0), 2)
    INTO :V_PROCUREMENT_OTD
    FROM SC_ONTOLOGY.LEGACY.VW_PROCUREMENT_OTD
    WHERE QUARTER_LABEL = 'Q3 2026';

    -- 3. Legacy Logistics Outbound OTD (Q3 2026: Sums on-time deliveries vs total delivered shipments)
    SELECT ROUND(100.0 * SUM(ON_TIME_DELIVERY_COUNT) / NULLIF(SUM(TOTAL_DELIVERIES), 0), 2)
    INTO :V_LOGISTICS_OTD
    FROM SC_ONTOLOGY.LEGACY.VW_LOGISTICS_OTD
    WHERE QUARTER_LABEL = 'Q3 2026';

    -- 4. Curated Canonical Outbound OTD (Q3 2026: Order dates in Q3 2026 on conformed fact)
    SELECT ROUND(100.0 * COUNT(CASE WHEN IS_ON_TIME_OUTBOUND = TRUE THEN 1 END) / NULLIF(COUNT(CASE WHEN IS_DELIVERED = TRUE THEN 1 END), 0), 2)
    INTO :V_CANONICAL_OTD
    FROM SC_ONTOLOGY.CURATED.FACT_OUTBOUND_SHIPMENTS
    WHERE ORDER_DATE BETWEEN '2026-07-01' AND '2026-09-30';

    -- Compute max delta against canonical
    V_MAX_DELTA := GREATEST(
        ABS(COALESCE(:V_PLANNING_OTD, 0) - COALESCE(:V_CANONICAL_OTD, 0)),
        ABS(COALESCE(:V_PROCUREMENT_OTD, 0) - COALESCE(:V_CANONICAL_OTD, 0)),
        ABS(COALESCE(:V_LOGISTICS_OTD, 0) - COALESCE(:V_CANONICAL_OTD, 0))
    );

    -- Drift Threshold: abs delta > 0.5 percentage points between canonical and legacy outbound logistics = DRIFT
    -- Canonical (64.12) and Legacy Logistics (64.12) are numerically aligned (delta = 0.0), logged as ALIGNED.
    IF (ABS(COALESCE(:V_LOGISTICS_OTD, 0) - COALESCE(:V_CANONICAL_OTD, 0)) <= 0.5) THEN
        V_STATUS := 'ALIGNED';
    ELSE
        V_STATUS := 'DRIFT';
    END IF;

    V_LOG_ID := 'DFT-' || TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD-HH24MISS');

    INSERT INTO SC_ONTOLOGY.APP.CONSISTENCY_LOG (
        LOG_ID, CHECK_TIMESTAMP, METRIC_NAME, 
        LEGACY_PLANNING_VAL, LEGACY_PROCUREMENT_VAL, LEGACY_LOGISTICS_VAL, 
        CURATED_CANONICAL_VAL, DELTA_MAX, STATUS
    ) VALUES (
        :V_LOG_ID, CURRENT_TIMESTAMP(), 'Outbound_OTD_Q3_2026',
        :V_PLANNING_OTD, :V_PROCUREMENT_OTD, :V_LOGISTICS_OTD,
        :V_CANONICAL_OTD, :V_MAX_DELTA, :V_STATUS
    );

    RETURN 'SUCCESS: Drift Check completed (' || :V_STATUS || '). Curated Canonical=' || COALESCE(:V_CANONICAL_OTD,0) || '%, Legacy Log=' || COALESCE(:V_LOGISTICS_OTD,0) || '%, Legacy Plan=' || COALESCE(:V_PLANNING_OTD,0) || '%, Legacy Proc=' || COALESCE(:V_PROCUREMENT_OTD,0) || '%. Logged as ' || :V_LOG_ID;
END;
$$;

-- 2. Governance Health Status Board View
CREATE OR REPLACE VIEW GOVERNANCE.V_GOVERNANCE_HEALTH AS
WITH latest_runs AS (
    SELECT 
        LOG_ID,
        CHECK_TIMESTAMP AS LAST_CHECKED,
        METRIC_NAME,
        CURATED_CANONICAL_VAL AS CANONICAL_VALUE,
        LEGACY_LOGISTICS_VAL,
        LEGACY_PLANNING_VAL,
        LEGACY_PROCUREMENT_VAL,
        ROUND(CURATED_CANONICAL_VAL - LEGACY_LOGISTICS_VAL, 2) AS DELTA_VS_LOGISTICS,
        ROUND(CURATED_CANONICAL_VAL - LEGACY_PLANNING_VAL, 2) AS DELTA_VS_PLANNING,
        ROUND(CURATED_CANONICAL_VAL - LEGACY_PROCUREMENT_VAL, 2) AS DELTA_VS_PROCUREMENT,
        DELTA_MAX,
        STATUS,
        ROW_NUMBER() OVER (PARTITION BY METRIC_NAME ORDER BY CHECK_TIMESTAMP DESC) AS RN
    FROM SC_ONTOLOGY.APP.CONSISTENCY_LOG
)
SELECT 
    METRIC_NAME,
    CANONICAL_VALUE,
    LEGACY_LOGISTICS_VAL,
    LEGACY_PLANNING_VAL,
    LEGACY_PROCUREMENT_VAL,
    DELTA_VS_LOGISTICS,
    DELTA_VS_PLANNING,
    DELTA_VS_PROCUREMENT,
    DELTA_MAX,
    STATUS,
    LAST_CHECKED,
    LOG_ID
FROM latest_runs
WHERE RN = 1;

-- 3. Suspended Scheduled Task Calling Drift Check
CREATE OR REPLACE TASK GOVERNANCE.TSK_DRIFT_SENTINEL
    WAREHOUSE = HACK_WH
    SCHEDULE = '1440 MINUTE'
AS
CALL GOVERNANCE.SP_RUN_DRIFT_CHECK();

-- Keep task explicitly SUSPENDED for cost control
ALTER TASK GOVERNANCE.TSK_DRIFT_SENTINEL SUSPEND;
